name: kucoweb CI/CD
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: test kucoweb
    runs-on: ubuntu-22.04
    steps:
    - name: check out repository
      uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle
      
    - name: grant execution permission to ./accountant/gradlew
      run: chmod +x ./accountant/gradlew
      
    - name: test with gradle
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: ./accountant/
    
    - name: upload test result
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: ./accountant/build/test-report.html
  
  build:
    name: build and run kucoweb on remote server
    needs: [test]
    if: success() && needs.test.result == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /share/kuco
            sh deploy.sh
